@startuml
scale 1.0
autonumber
skinparam SequenceMessageAlign center
skinparam ParticipantPadding 60
participant EGG_App
database RDBMS
participant API_Gateway
participant Batch_Daemon
database Redis
Batch_Daemon ->> Redis: 기기 필드 값 해시 테이블 저장
||10||
loop 10 second
    Redis ->>  Batch_Daemon : 해시 테이블 읽기
    ||10||
end
Batch_Daemon -->> API_Gateway: POST request (Abnormal Field)
API_Gateway --> RDBMS: SQL query request
activate RDBMS
RDBMS --> API_Gateway: SQL query response
deactivate RDBMS
||20||
API_Gateway -->> EGG_App: Push request
EGG_App -->> Batch_Daemon: GET request (URL etc.)
activate Batch_Daemon
Batch_Daemon -->> EGG_App: POST response (URL etc.)
deactivate Batch_Daemon
||10||
@enduml

